### ISSUE TITLE
Wrong test into carbon-dating.test.js

### ISSUE THREAD

**Issue by chebb44** [AlreadyBored/basic-js#10]
str 54
assert.equal(dateSample('11.3231.3213124'), 2326);
the extra point.

**Comment by AlreadyBored** [comment]
It's a feature :)
There is a built-in method in javascript to correctly convert a string containing a floating-point number to a number, use it.

**Comment by kagafon** [comment]
Due to task description, parameter should be a correct number. parseFloat() will truncate number to 11.3231 with loosing of some data. As for me it is a feature for JS but a bug for the task.
