### ISSUE TITLE
FYI: ELIFECYCLE error

### ISSUE THREAD

**Issue by ThorsAngerVaNeT** [AlreadyBored/basic-js#105]
Уже у двух студентов JS/FE 2022Q1 обнаружилась такая ошибка, почему-то помогает глобальная установка node-gyp:
`npm install -g node-gyp`
![image](https://user-images.githubusercontent.com/17920285/158375305-f54d87fa-6f42-402f-af25-10b233d98cf9.png)
![image](https://user-images.githubusercontent.com/17920285/158375328-308b1263-defb-45f1-9b06-18f8da7034b7.png)
Просто решил проинформировать.

**Comment by AlreadyBored** [comment]
Thanks for the information, I'll update corresponding docs!
