### ISSUE TITLE
Link to the article about Carbon Dating doesn't work.

### ISSUE THREAD

**Issue by ksarise** [AlreadyBored/basic-js#161]
When following link it refuses the request.
![image](https://github.com/AlreadyBored/basic-js/assets/18985111/24264deb-8c1f-4773-bf38-c286f0e37e63)
Sounds like temporary overload, but
Maybe it will be useful to add a reserved link to webarchive's [capture](https://web.archive.org/web/20231208073553/https://chem.libretexts.org/Bookshelves/Physical_and_Theoretical_Chemistry_Textbook_Maps/Supplemental_Modules_(Physical_and_Theoretical_Chemistry)/Nuclear_Chemistry/Nuclear_Kinetics/Half-Lives_and_Radioactive_Decay_Kinetics#section_2)?

**Comment by AlreadyBored** [comment]
thx!
