### ISSUE TITLE
Transform array (error in test and need explanation)

### ISSUE THREAD

**Issue by enl001** [AlreadyBored/basic-js#17]
Hello!
1. Look at the screenshot. Infinity should be at the first place.
![Error](https://user-images.githubusercontent.com/57068526/75113880-b6178580-5662-11ea-80e8-fe6c3cdc37a1.PNG)
2. Explain please what "--double-prev" should do:  double previous item of the input array or simply add another instance of the previos item. 
Situation: ["--discard-next", x, "--double-prev, y"]
 a. y           - we discard **x**, so nothing to double
 b. [x, y]     - discard **x** then add another **x** when double
 c. [ x, x, y] - simply double previous.

Best regards,
Slava

**Comment by AlreadyBored** [comment]
Hello! Explained by points:
1. There's no error, look at the attached picture.
![explanation](https://user-images.githubusercontent.com/34455330/75152097-529c5f00-5719-11ea-8590-0749e5b22cd8.png)
2. Correct answer is **b**

**Comment by enl001** [comment]
Hello!
I understand, that it is another Infinity. From my point of view there should be another Infinity at the first plase.

> --discard-prev excludes the **_previous element of the array_** from the transformed array

So, I assum, that it works like this: 
![Error1](https://user-images.githubusercontent.com/57068526/75166919-ad43b400-5735-11ea-9cdf-403b7e5afa5d.PNG)

Sorry for quality.
If it works like you showed, so :
![Error2](https://user-images.githubusercontent.com/57068526/75167365-4d99d880-5736-11ea-8488-a33d03d73356.PNG)

Clarification needed.

Best regards,
Slava
