### ISSUE TITLE
Transform array (need clarification)

### ISSUE THREAD

**Issue by enl001** [AlreadyBored/basic-js#19]
Hello!
I understand, that it is another Infinity. From my point of view there should be another Infinity at the first place.

> --discard-prev` excludes the **_previous element of the array_** from the transformed array

So, I assum, that it works like this:
![Error1](https://user-images.githubusercontent.com/57068526/75168115-6e166280-5737-11ea-9f61-9e764b61de9b.PNG)

If it works like you showed, so :
![Error2](https://user-images.githubusercontent.com/57068526/75168152-7a9abb00-5737-11ea-8f2e-46f2f13e49fe.PNG)

Clarification needed.

Best regards,
Slava

PS Sorry for quality.

**Comment by enl001** [comment]
Sorry for my perseverance. I don't want to prove that tests are wrong, I only want to figure out how it works exactly.

If we work with input array we perform command (discard(delete) instance, delete command from input array) so we have nothing to double with --double-prev  in second img.
if we don't delete from input array we should work with exactly previous instanse (when --x-prev).
We don't know anything about previous control sequences in this case.

Best regards,
Slava

**Comment by AlreadyBored** [comment]
The main idea of this task is that **we don't iterate** over the array from left to right, and the function transforms the array based on all available control sequences **at the same time**.
Iterating over the array from left to right, gradually changing the original array is the **wrong** solution.
I agree that this point should be specified in the task decscription, which, most likely, will be done after the deadline.

**Comment by enl001** [comment]
Thank you for your explanation :)

Best regards,
Slava

**Comment by enl001** [comment]
A priority need to be given to the control sequences I think to escape situations like in the first image of this issue (19). (to apply discard-prev to Inf (4->2)).
