### ISSUE TITLE
Transform array. Unclear order

### ISSUE THREAD

**Issue by filland** [AlreadyBored/basic-js#21]
I added some console.log() in the test for the Transform Array task and found that  when the input array looks like this:
` ["--discard-next", 22, "--double-prev"] `
The output result of the transformation looks like this:
`[22]`
This means that the control sequences were resolved starting from the end. But I did not find any info about the side from which I should start. I used to think that we start from the first element and should get the following result in this case:
`[]` (an empty array)

Could you please clarify this?
Thanks

**Comment by AlreadyBored** [comment]
Look in the pinned messages in the discord channel #stage1-algorithmic-tasks, there is an answer to your question.
