### ISSUE TITLE
There can be issue with 'transform array' task

### ISSUE THREAD

**Issue by limpid-kzonix** [AlreadyBored/basic-js#30]
![image](https://user-images.githubusercontent.com/8176996/83311461-fd8c4f80-a217-11ea-9cc7-db315f32920d.png)
original array 
```[--discard-next,555,--discard-next,[object Object],DEF,--double-prev]```

should not require such output 
```[[object Object],DEF,DEF]```

Control sequences are applied **from left to right**
`555` should be skipped, after that object should be skipped with a similar rule. 

Seems like `createSample` method in a tests doesn't work correct.
![image](https://user-images.githubusercontent.com/8176996/83311772-e5690000-a218-11ea-9a2e-f73420621cc5.png)

**Comment by AlreadyBored** [comment]
Thx, I'll figure it out

**Comment by AlreadyBored** [comment]
solved
