### ISSUE TITLE
Ошибка в тесте для "Расширенный повторитель"

### ISSUE THREAD

**Issue by Fodin** [AlreadyBored/basic-js#48]
В ТЗ написано: "repeatTimes и additionRepeatTimes являются целыми числами (в случае отсутствия любого из них соответствующая строка не повторяется)."
И тут же от меня хотят: 
assert.equal(repeater('TESTstr', { repeatTimes: undefined, separator: 'ds', addition: 'ADD!', additionRepeatTimes: undefined, additionSeparator: ')))000' }), 'TESTstrADD!');
Ожидаемое поведение противоречит условиям ТЗ. undefined- не число.  При этом почему-то на выходе ожидается str + options.addition, но без сепараторов.

Решил задачу вот так:
if (options.repeatTimes === undefined && options.additionRepeatTimes === undefined) {
    return "TESTstrADD!";
  }

**Comment by AlreadyBored** [comment]
Поскольку при попытке обращения к непереданному аргументу будет получен undefined, в большинстве случаев явная передача undefined будет эквивалентна. Но, возможно, стоит пересмотреть этот тест.

**Comment by Fodin** [comment]
Так это ведь не передача пустого аргумента в функцию, а свойство объекта, переданного в нее. Оно объявлено (declared), но установлено в undefined.
Ну, даже пусть так, приравняем к отсутствию опции. Возвращаемое значение очень странное получается.

**Comment by AlreadyBored** [comment]
Тест этот и другие аналогичные будут пересмотрены, концептуально это не очень правильно.
Но я не очень представляю, каким образом при обычной проверке на то, передан ли аргумент-число, если аргумент не передан, будет один результат, а если передан undefined, будет другой. Разве что лезть в псевдомассив arguments зачем-то и там что-то сравнивать. Поэтому поменять это нужно, но решение, написанное в соответствии с условиями задачи, пройдет эти тесты без проблем.

**Comment by Fodin** [comment]
Не могу понять, почему при undefined параметрах повтора (мы же их как нули воспринимать должны?) в тесте ожидается значение "TESTstrADD!". Должна ведь вернуться пустая строка. 
Мое решение без воркэраунда не проходит только этот тест. Именно потому, что возвращает пустую строку.
Зато если изменить тест на вот такой, то проходит:
assert.equal(repeater('TESTstr', { repeatTimes: **1**, separator: 'ds', addition: 'ADD!', additionRepeatTimes: **1**, additionSeparator: ')))000' }), 'TESTstrADD!');

**Comment by GuyFox70** [comment]
Добрый день! Можно в принципе передать объект с одноименными параметрами вместо 'option' и присвоить значение по умолчанию в случае undefined. Если я правильно понял о чем речь. У меня другой вопрос! В задаче написано additionSeparator default value is '|', но при тесте выходит что он по умолчанию просто ".

**Comment by AlreadyBored** [comment]
> Добрый день! Можно в принципе передать объект с одноименными параметрами вместо 'option' и присвоить значение по умолчанию в случае undefined. Если я правильно понял о чем речь. У меня другой вопрос! В задаче написано additionSeparator default value is '|', но при тесте выходит что он по умолчанию просто ".

Скорее всего, дело в том, что он не всегда нужен. Если `addinition` не повторяется, то и разделитель там ставить не нужно, в этом случае его не будет.

**Comment by AlreadyBored** [comment]
Убраны тесты, где явно передается undefined в качестве значений свойств объекта options, добавлены тесты, где проверяется правильное использование значений separator и additionSeparator по умолчанию
