### ISSUE TITLE
Transform array

### ISSUE THREAD

**Issue by Vimbi** [AlreadyBored/basic-js#55]
В условиях Control sequences are applied from left to right.
В тестах doubleDiscarded: {
                    input: [1, 2, 3, '--discard-next', 1337, '--double-prev', 4, 5],
                    output: [1, 2, 3, 4, 5]
                }
Разве ответ не [1, 2, 3, 3, 4, 5].
Сначала происходит удаление 1337, затем дублируется 3.

input: [1, 2, 3, '--discard-next', 1337, '--discard-prev', 4, 5],
                    output: [1, 2, 3, 4, 5]
Аналогично, сначала удаляется 1337, затем удаляется 3 и ответ [1, 2, 4, 5]

**Comment by AlreadyBored** [comment]
В условии прописано, что последовательности применяются к тем элементам, которые _непосредственно_ находятся рядом с ними в исходном массиве. Поэтому все соответствует условию
