### ISSUE TITLE
Extended repeater

### ISSUE THREAD

**Issue by Vimbi** [AlreadyBored/basic-js#57]
Добрый день.
В Extended repeater есть условие 

"The str and addition parameters are strings by default. In case when type of these parameters is different, they must be converted to a string."

Но в тестах это условие кажется не проверяется.

**Comment by AlreadyBored** [comment]
Добрый день. Почему же, в тестах это проверяется вот здесь
![image](https://user-images.githubusercontent.com/34455330/109194030-12e3d980-77aa-11eb-9cc1-6b14d19f58a8.png)

**Comment by AlreadyBored** [comment]
Впрочем, возможно, здесь требуются дополнительные тесты

**Comment by AlreadyBored** [comment]
Сделан отдельный тест, где объект, передаваемый в качестве str и addition, явно приводится к строке.
