### ISSUE TITLE
"it.optional is not a function" TypeError in carbon-dating tests

### ISSUE THREAD

**Issue by VladSelikh** [AlreadyBored/basic-js#60]
I have a TypeError thrown after launching tests for carbon-dating task:
"it.optional is not a function".

ATTENTION! Only reproduced after passing "npm run test ./test/carbon-dating.test.js" command to the prompt (not "npm run test").

I believe that is because there is "it.optional" nested in another "it.optional" function, as we have two valid returns for each 1 parameter passed to our function and that nesting causes context being lost.
![Screen1](https://user-images.githubusercontent.com/68236287/106370939-1c774e80-6370-11eb-855a-47450d4757ab.PNG)

See when I comment upper-level "it.optional" function (screenshot is attached) the error disappears and all tests pass.
I would also recommend replacing the "it.optional" nested function with describe. In this very case tests pass too.
![Screen2](https://user-images.githubusercontent.com/68236287/106371357-8691f280-6374-11eb-8266-88cfc7a2c1fe.PNG)

Please resolve this problem.

Looking forward to your soonest reply.

**Comment by AlreadyBored** [comment]
Solved. Now you can run tests separately by passing the path to the file with tests using the syntax "npm run test <path to file with tests>"
