### ISSUE TITLE
Уточнение в условии таска

### ISSUE THREAD

**Issue by igorlyatskiy** [AlreadyBored/basic-js#69]
Добавление уточнения: "Необходимо почистить код от console.log() перед сабмитом, иначе автотест может не засчитать задание".

**Comment by unsky559** [comment]
Не думаю что это должно быть указано в задании. Ваши готовые функции никогда не должны спамить в консоль ненужную информацию. Более того эти операции достаточно ресурсоёмкие и могут значительно увеличивать время работы скипта, особенно если вы выводите в консоль большие сущности.

**Comment by AlreadyBored** [comment]
Во-первых, отладочный вывод в консоль, как правило, должен быть удален по завершении работ, во-вторых, сам по себе вывод в консоль не препятствует решению задач, это скорее вопрос того, как это решение проверяется школой, поэтому не считаю нужным вносить это в документацию репозитория.
