### ISSUE TITLE
Hanoi Tower tests

### ISSUE THREAD

**Issue by sovaz1997** [AlreadyBored/basic-js#9]
Hanoi Tower:

I think that it is necessary to reduce the accuracy of the check, because there are 16 decimal places here, which exceeds machine accuracy. Reduce to at least 12 will be good I think :)

```
{
-  "seconds": 1.6502813140731935e+217
+  "seconds": 1.6502813140731933e+217
"turns": 3.6147378671465184e+221
}
```

**Comment by sovaz1997** [comment]
For example, you can check that the number is close enough to the solution (the difference between the values is less than 10 ** -12)

**Comment by AlreadyBored** [comment]
At the moment, various valid solutions to this task will pass the tests. For the future, this needs to be considered. Do you mean using something like closeTo instead of a strict comparison?

**Comment by sovaz1997** [comment]
I don't know exactly how this is implemented)
Like Math.abs (value - realValue) <= 10 ** -10

**Comment by dvoryadkin1989** [comment]
Have the same issue with accuracy. My solution seems to be correct as fifference is negligible.
```javascript
       {
      -  "seconds": 1.6502813140731935e+217
      +  "seconds": 1.6502813140731933e+217
         "turns": 3.6147378671465184e+221
       }
```

 Do I nead to amend my solution in any way? Or test accuracy will be reduced?

**Comment by AlreadyBored** [comment]
> Have the same issue with accuracy. My solution seems to be correct as difference is negligible.
> 
> ```js
>        {
>       -  "seconds": 1.6502813140731935e+217
>       +  "seconds": 1.6502813140731933e+217
>          "turns": 3.6147378671465184e+221
>        }
> ```
> 
> Do I nead to amend my solution in any way? Or test accuracy will be reduced?

You should submit the solution that passes the tests. Changes to the tests will be made after the deadline.

**Comment by AlreadyBored** [comment]
Solved
